import { InvitationStatus } from "../components/exhibitorInvitations/statusOfSentInvitations/StatusOfSentInvitations";
import { _AddedEvent } from "../types/types";

export const mockInvitations: {
  id: number;
  fullName: string;
  email: string;
  status: InvitationStatus;
  reminder?: boolean;
}[] = [
  { id: 1, fullName: "Jan Kowalski", email: "jan.kowalski@example.com", status: "Wysłane" },
  { id: 2, fullName: "Anna Nowak", email: "anna.nowak@example.com", status: "Aktywowane"},
  { id: 3, fullName: "Piotr Wiśniewski", email: "piotr.wisniewski@example.com", status: "Potwierdzone", reminder: true },
  { id: 4, fullName: "Katarzyna Zielińska", email: "katarzyna.zielinska@example.com", status: "Wysłane" },
  { id: 5, fullName: "Michał Wójcik", email: "michal.wojcik@example.com", status: "Potwierdzone", reminder: false },
  { id: 6, fullName: "Agnieszka Kamińska", email: "agnieszka.kaminska@example.com", status: "Aktywowane", reminder: true },
  { id: 7, fullName: "Tomasz Lewandowski", email: "tomasz.lewandowski@example.com", status: "Wysłane" },
  { id: 8, fullName: "Magdalena Szymańska", email: "magda.szymanska@example.com", status: "Wysłane", reminder: true },
  { id: 9, fullName: "Paweł Woźniak", email: "pawel.wozniak@example.com", status: "Aktywowane", reminder: false },
  { id: 10, fullName: "Ewa Kozłowska", email: "ewa.kozlowska@example.com", status: "Potwierdzone", reminder: false },
  { id: 11, fullName: "Marcin Jankowski", email: "marcin.jankowski@example.com", status: "Wysłane"},
  { id: 12, fullName: "Joanna Mazur", email: "joanna.mazur@example.com", status: "Aktywowane", reminder: false },
  { id: 13, fullName: "Grzegorz Krawczyk", email: "grzegorz.krawczyk@example.com", status: "Potwierdzone", reminder: true },
  { id: 14, fullName: "Paulina Piotrowska", email: "paulina.piotrowska@example.com", status: "Wysłane", reminder: false }
];

export const sampleEvents: _AddedEvent[] = [
  {
    id: 1,
    exhibition_id: 101,
    name: 'Event 1',
    eventDate: '2025-09-01',
    startTime: '09:00',
    endTime: '12:00',
    eventType: 'Montaż stoiska',
    eventTitle: 'Konferencja branżowa',
    description: 'Opis konferencji dotyczącej nowych technologii.',
    organizer: 'Organizator A',
    addedToOfficialCatalog: false,
  },
  {
    id: 2,
    exhibition_id: 102,
    name: 'Event 2',
    eventDate: '2025-09-02',
    startTime: '10:00',
    endTime: '14:00',
    eventType: 'Demontaż stoiska',
    eventTitle: 'Warsztaty programistyczne',
    description: 'Ogólnie znana teza głosi, iż użytkownika może rozpraszać zrozumiała zawartość strony, kiedy ten chce zobaczyć sam jej wygląd. Jedną z mocnych stron używania Lorem Ipsum jest to, że ma wiele różnych „kombinacji” zdań, słów i akapitów, w przeciwieństwie do zwykłego: „tekst, tekst, tekst”, sprawiającego, że wygląda to „zbyt czytelnie” po polsku. Wielu webmasterów i designerów używa Lorem Ipsum jako domyślnego modelu tekstu i wpisanie w internetowej wyszukiwarce ‘lorem ipsum’ spowoduje znalezienie bardzo wielu stron, które wciąż są w budowie. Wiele wersji tekstu ewoluowało i zmieniało się przez lata, czasem przez przypadek, czasem specjalnie (humorystyczne wstawki itd).',
    organizer: 'Organizator B',
    isDelete: false,
    isEdited: false,
  },
  {
    id: 3,
    exhibition_id: 103,
    name: 'Event 3',
    eventDate: '2025-09-03',
    startTime: '11:00',
    endTime: '15:00',
    eventType: 'Prezentacja produktów i marek',
    eventTitle: 'Wystawa sztuki nowoczesnej',
    description: 'Ogólnie znana teza głosi, iż użytkownika może rozpraszać zrozumiała zawartość strony, kiedy ten chce zobaczyć sam jej wygląd. Jedną z mocnych stron używania Lorem Ipsum jest to, że ma wiele różnych „kombinacji” zdań, słów i akapitów, w przeciwieństwie do zwykłego: „tekst, tekst, tekst”, sprawiającego, że wygląda to „zbyt czytelnie” po polsku. Wielu webmasterów i designerów używa Lorem Ipsum jako domyślnego modelu tekstu i wpisanie w internetowej wyszukiwarce ‘lorem ipsum’ spowoduje znalezienie bardzo wielu stron, które wciąż są w budowie. Wiele wersji tekstu ewoluowało i zmieniało się przez lata, czasem przez przypadek, czasem specjalnie (humorystyczne wstawki itd).',
    organizer: 'Organizator C',
    addedToOfficialCatalog: true,
  },
  {
    id: 4,
    exhibition_id: 104,
    name: 'Event 4',
    eventDate: '2025-09-04',
    startTime: '13:00',
    endTime: '17:00',
    eventType: 'Edukacyjne i eksperckie',
    eventTitle: '',
    description: 'Pokaz nowego urządzenia elektronicznego.',
    organizer: 'Organizator D',
    isDelete: true,
    isEdited: true,
  },
  {
    id: 5,
    exhibition_id: 105,
    name: 'Event 5',
    eventDate: '2025-09-05',
    startTime: '08:30',
    endTime: '11:30',
    eventType: 'Dostawa i montaż sprzętu/materiałów',
    eventTitle: 'Seminarium naukowe',
    description: 'Wykłady specjalistów z branży medycznej.',
    organizer: 'Organizator E',
    addedToOfficialCatalog: false,
  },
  {
    id: 6,
    exhibition_id: 106,
    name: 'Event 6',
    eventDate: '2025-09-06',
    startTime: '15:00',
    endTime: '18:00',
    eventType: 'Montaż stoiska',
    eventTitle: 'Warsztaty kreatywnego pisania',
    description: 'Zajęcia z pisania literackiego i storytellingu.',
    organizer: 'Organizator F',
    isDelete: false,
    isEdited: false,
  },
  {
    id: 7,
    exhibition_id: 107,
    name: 'Event 7',
    eventDate: '2025-09-07',
    startTime: '09:30',
    endTime: '11:30',
    eventType: 'Demontaż stoiska',
    eventTitle: 'Spotkanie networkingowe',
    description: 'Networking branżowy dla profesjonalistów.',
    organizer: 'Organizator G',
    addedToOfficialCatalog: true,
  },
  {
    id: 8,
    exhibition_id: 108,
    name: 'Event 8',
    eventDate: '2025-09-08',
    startTime: '12:00',
    endTime: '14:00',
    eventType: 'Prezentacja produktów i marek',
    eventTitle: 'Prezentacja nowej kolekcji',
    description: 'Wydarzenie prezentujące nową linię produktów.',
    organizer: 'Organizator H',
    isDelete: true,
    isEdited: false,
  },
  {
    id: 9,
    exhibition_id: 109,
    name: 'Event 9',
    eventDate: '2025-09-09',
    startTime: '10:00',
    endTime: '16:00',
    eventType: 'Edukacyjne i eksperckie',
    eventTitle: 'Seminarium edukacyjne',
    description: 'Edukacja na temat najnowszych trendów technologicznych.',
    organizer: 'Organizator I',
    addedToOfficialCatalog: false,
  },
  {
    id: 10,
    exhibition_id: 110,
    name: 'Event 10',
    eventDate: '2025-09-10',
    startTime: '09:00',
    endTime: '12:00',
    eventType: 'Dostawa i montaż sprzętu/materiałów',
    eventTitle: 'Logistyka wydarzenia',
    description: 'Koordynacja dostaw i montażu sprzętu.',
    organizer: 'Organizator J',
    isDelete: true,
    isEdited: true,
  },
  {
    id: 11,
    exhibition_id: 111,
    name: 'Event 11',
    eventDate: '2025-09-11',
    startTime: '13:00',
    endTime: '15:00',
    eventType: 'Montaż stoiska',
    eventTitle: 'Prezentacja produktu',
    description: 'Demonstracja produktu na stoisku.',
    organizer: 'Organizator K',
    addedToOfficialCatalog: false,
  },
  {
    id: 12,
    exhibition_id: 112,
    name: 'Event 12',
    eventDate: '2025-09-12',
    startTime: '14:00',
    endTime: '17:00',
    eventType: 'Demontaż stoiska',
    eventTitle: 'Zakończenie wystawy',
    description: 'Procedury demontażu i zakończenia wydarzenia.',
    organizer: 'Organizator L',
    isDelete: false,
    isEdited: false,
  },
  {
    id: 13,
    exhibition_id: 113,
    name: 'Event 13',
    eventDate: '2025-09-13',
    startTime: '09:00',
    endTime: '13:00',
    eventType: 'Prezentacja produktów i marek',
    eventTitle: 'Promocja produktów',
    description: 'Warsztaty promocyjne i marketingowe.',
    organizer: 'Organizator M',
    addedToOfficialCatalog: true,
  },
  {
    id: 14,
    exhibition_id: 114,
    name: 'Event 14',
    eventDate: '2025-09-14',
    startTime: '10:00',
    endTime: '12:00',
    eventType: 'Edukacyjne i eksperckie',
    eventTitle: 'Szkolenie specjalistyczne',
    description: 'Program szkoleniowy dla ekspertów branżowych.',
    organizer: 'Organizator N',
    isDelete: true,
    isEdited: false,
  },
  {
    id: 15,
    exhibition_id: 115,
    name: 'Event 15',
    eventDate: '2025-09-15',
    startTime: '11:00',
    endTime: '15:00',
    eventType: 'Dostawa i montaż sprzętu/materiałów',
    eventTitle: 'Koordynacja techniczna',
    description: 'Zarządzanie dostawą i montażem materiałów.',
    organizer: 'Organizator O',
    addedToOfficialCatalog: false,
  },
];

// export const sampleEvents: _AddedEvent[] = [
//   {
//     id: 1,
//     exhibition_id: 101,
//     name: 'Event 1',
//     eventDate: '2025-08-25',
//     startTime: '09:00',
//     endTime: '12:00',
//     eventType: 'Montaż stoiska',
//     eventTitle: 'Konferencja branżowa',
//     description: 'W przeciwieństwie do rozpowszechnionych opinii, Lorem Ipsum nie jest tylko przypadkowym tekstem. Ma ono korzenie w klasycznej łacińskiej literaturze z 45 roku przed Chrystusem, czyli ponad 2000 lat temu! Richard McClintock, wykładowca łaciny na uniwersytecie Hampden-Sydney w Virginii, przyjrzał się uważniej jednemu z najbardziej niejasnych słów w Lorem Ipsum – consectetur – i po wielu poszukiwaniach odnalazł niezaprzeczalne źródło: Lorem Ipsum pochodzi z fragmentów (1.10.32 i 1.10.33) „de Finibus Bonorum et Malorum”, czyli „O granicy dobra i zła”, napisanej właśnie w 45 p.n.e. przez Cycerona. Jest to bardzo popularna w czasach renesansu rozprawa na temat etyki. Pierwszy wiersz Lorem Ipsum, „Lorem ipsum dolor sit amet...” pochodzi właśnie z sekcji 1.10.32.',
//     organizer: 'Organizator A',
//     isDelete: false,
//     isEdited: false,
//     addedToOfficialCatalog: false,
//   },
//   {
//     id: 2,
//     exhibition_id: 102,
//     name: 'Event 2',
//     eventDate: '2025-08-26',
//     startTime: '10:00',
//     endTime: '14:00',
//     eventType: 'Demontaż stoiska',
//     eventTitle: 'Warsztaty programistyczne',
//     description: 'Praktyczne szkolenie z React i TypeScript.',
//     organizer: 'Organizator B',
//     isDelete: false,
//     addedToOfficialCatalog: true,
//   },
//   {
//     id: 3,
//     exhibition_id: 103,
//     name: 'Event 3',
//     eventDate: '2025-08-27',
//     startTime: '11:00',
//     endTime: '15:00',
//     eventType: 'Prezentacja produktów i marek',
//     eventTitle: 'Wystawa sztuki nowoczesnej',
//     description: 'Ekspozycja prac lokalnych artystów.',
//     organizer: 'Organizator C',
//     isDelete: true,
//     isEdited: true,
//     addedToOfficialCatalog: false,
//   },
//   {
//     id: 4,
//     exhibition_id: 105,
//     name: 'Event 5',
//     eventDate: '2025-08-29',
//     startTime: '08:30',
//     endTime: '11:30',
//     eventType: 'Dostawa i montaż sprzętu/materiałów',
//     eventTitle: 'Seminarium naukowe',
//     description: 'Wykłady specjalistów z branży medycznej.',
//     organizer: 'Organizator E',
//     addedToOfficialCatalog: true,
//   },
//   {
//     id: 5,
//     exhibition_id: 106,
//     name: 'Event 6',
//     eventDate: '2025-08-30',
//     startTime: '15:00',
//     endTime: '18:00',
//     eventType: 'Dostawa i montaż sprzętu/materiałów',
//     eventTitle: 'Warsztaty kreatywnego pisania',
//     description: 'Zajęcia z pisania literackiego i storytellingu.',
//     organizer: 'Organizator F',
//     addedToOfficialCatalog: false,
//   },
// ];